import time, sys
while True :


    print('              .')
    time.sleep(0.02)
    print('             ...')
    time.sleep(0.02)
    print('            .....')
    time.sleep(0.02)
    print('           .......')
    time.sleep(0.02)
    print('          .........')
    time.sleep(0.02)
    print('         ...........')
    time.sleep(0.02)
    print('        .............')
    time.sleep(0.02)
    print('       ...............')
    time.sleep(0.02)
    print('      .................')
    time.sleep(0.02)
    print('     ....           ....')
    time.sleep(0.02)
    print('    ...               ...')
    time.sleep(0.02)
    print('   ..                   ..')
    time.sleep(0.02)
    print('  .                       .')
    time.sleep(0.02)
    print('   ..                   ..')
    time.sleep(0.02)
    print('    ...               ...')
    time.sleep(0.02)
    print('     ....           ....')
    time.sleep(0.02)
    print('      .................')
    time.sleep(0.02)
    print('       ...............')
    time.sleep(0.02)
    print('        .............')
    time.sleep(0.02)
    print('         ...........')
    time.sleep(0.02)
    print('          .........')
    time.sleep(0.02)
    print('           .......')
    time.sleep(0.02)
    print('            .....')
    time.sleep(0.02)
    print('             ...')
    time.sleep(0.02)
    print('              .')
    time.sleep(0.02)
    print(' ')
